// ============================================================
//  fft_twiddle_rom.v
//  Twiddle Factor ROM for 1024-point FFT
//  Stores W_N^k = cos(2*pi*k/N) - j*sin(2*pi*k/N), k=0..511
//  Fixed-point: 18-bit signed, Q1.17 format
//  (range -1.0 to +1.0 mapped to -131072 to +131071)
// ============================================================
module fft_twiddle_rom #(
    parameter DATA_WIDTH = 18,
    parameter NFFT       = 1024,
    parameter HALF       = NFFT/2   // 512 entries
)(
    input  wire                         clk,
    input  wire [$clog2(HALF)-1:0]      addr,   // 0..511
    output reg  signed [DATA_WIDTH-1:0] cos_out, // real part
    output reg  signed [DATA_WIDTH-1:0] sin_out  // imag part (negative sine)
);

    // ROM arrays
    reg signed [DATA_WIDTH-1:0] cos_rom [0:HALF-1];
    reg signed [DATA_WIDTH-1:0] sin_rom [0:HALF-1];

    // Initialise from file generated by the Python/MATLAB script
    // File format: one value per line, signed decimal
    initial begin
        $readmemh("twiddle_cos.hex", cos_rom);
        $readmemh("twiddle_sin.hex", sin_rom);
    end

    always @(posedge clk) begin
        cos_out <= cos_rom[addr];
        sin_out <= sin_rom[addr];
    end

endmodule
